import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const runtime = "nodejs";

const TITLES: Record<string, string> = {
  monthly: "Monthly Portfolio Report",
  performance: "Commodity Performance Report",
  ai: "AI Market Prediction Report",
};

export async function GET(request: NextRequest) {
  const type = request.nextUrl.searchParams.get("type") ?? "monthly";
  const title = TITLES[type] ?? TITLES.monthly;

  const pdf = await PDFDocument.create();
  const page = pdf.addPage([612, 792]);
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const navy = rgb(11 / 255, 31 / 255, 51 / 255);
  const body = rgb(51 / 255, 65 / 255, 85 / 255);

  page.drawText(title, { x: 48, y: 720, size: 18, font: fontBold, color: navy });
  page.drawText("Generated by Commodity Analytics Dashboard", {
    x: 48,
    y: 690,
    size: 11,
    font,
    color: body,
  });
  page.drawText(
    "This PDF is generated server-side for export. Connect your data warehouse to enrich metrics.",
    { x: 48, y: 660, size: 10, font, color: body, maxWidth: 520 }
  );

  const bytes = await pdf.save();
  return new NextResponse(Buffer.from(bytes), {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${type}-report.pdf"`,
    },
  });
}
